# application.yml - Fixed R2DBC configuration
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # R2DBC Configuration (replaces JPA)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/donpetre #${DB_NAME:donpetre}
    username: don #${DB_USERNAME:don}
    password: don_pass #${DB_PASSWORD:don_pass}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # Flyway for database migrations
  flyway:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/donpetre #${DB_NAME:donpetre}
    user: don #${DB_USERNAME:don}
    password: don_pass #${DB_PASSWORD:don_pass}url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:donpetre}
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      database: 0

  # Spring Cloud Gateway Configuration
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s

      # Global filters
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE
            methods: GET,POST,PUT,DELETE

        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@userKeyResolver}"

      # Route definitions
      routes:
        - id: knowledge-ingestion-route
          uri: http://${INGESTION_SERVICE_HOST:localhost}:${INGESTION_SERVICE_PORT:8081}
          predicates:
            - Path=/api/ingestion/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: knowledge-ingestion
                fallbackUri: forward:/fallback/knowledge-ingestion

        - id: knowledge-management-route
          uri: http://${MANAGEMENT_SERVICE_HOST:localhost}:${MANAGEMENT_SERVICE_PORT:8082}
          predicates:
            - Path=/api/knowledge/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: knowledge-management
                fallbackUri: forward:/fallback/knowledge-management

        - id: search-service-route
          uri: http://${SEARCH_SERVICE_HOST:localhost}:${SEARCH_SERVICE_PORT:8083}
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: search-service
                fallbackUri: forward:/fallback/search-service

        - id: auth-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    gateway:
      enabled: true

# Logging Configuration
logging:
  level:
    com.openrangelabs.donpetre: ${LOG_LEVEL:DEBUG}
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.r2dbc: ${R2DBC_LOG_LEVEL:INFO}
    io.r2dbc: ${R2DBC_LOG_LEVEL:INFO}
    reactor.netty: ${NETTY_LOG_LEVEL:WARN}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

# Custom Application Configuration
open-range-labs:
  donpetre:
    security:
      jwt:
        secret: ${JWT_SECRET:}
        expiration: 86400000 # 24 hours in milliseconds
        refresh-expiration: 604800000 # 7 days in milliseconds
        algorithm: HS512
        key-length: 64
        auto-generate-secret: false
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    pool:
      initial-size: 2
      max-size: 10

logging:
  level:
    com.openrangelabs.donpetre: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

open-range-labs:
  donpetre:
    security:
      jwt:
        auto-generate-secret: true  # Allow auto-generation in dev only
      cors:
        allowed-origins: "http://localhost:3000,http://localhost:8080,http://localhost:8084"

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  r2dbc:
    pool:
      initial-size: 10
      max-size: 50

logging:
  level:
    com.openrangelabs.donpetre: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.security: WARN
    org.springframework.r2dbc: WARN

open-range-labs:
  donpetre:
    security:
      jwt:
        auto-generate-secret: false  # Never auto-generate in production

---
# Docker Profile - FIXED: Include database credentials
spring:
  config:
    activate:
      on-profile: docker

  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/donpetre
    username: don
    password: don_pass

  flyway:
    url: jdbc:postgresql://postgresql:5432/donpetre
    user: don
    password: don_pass

  data:
    redis:
      host: redis

logging:
  level:
    com.openrangelabs.donpetre: INFO